#!/bin/bash
# Path
if [ -x /usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator ]; then
  mapfile -t user_envs < <(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)
  export "${user_envs[@]}"
fi

export PATH="$PATH:$HOME/.local/share/nvim/mason/bin:$HOME/.config/emacs/bin"

export NTFY_TOPIC=ping
export NTFY_TAGS="$HOSTNAME"

export NVIM_LSP_ENABLED=true
