#!/bin/bash
export $(envsubst < "$HOME/.config/environment.d/env.conf")

export PAGER="bat -p"
export READER="zathura"
export BROWSER="firefox"
export GOPATH="$HOME/go"

export PATH="$PATH:$HOME/.local/bin/:$XDG_DATA_HOME/nvim/mason/bin:$XDG_CONFIG_HOME/emacs/bin:$GOPATH/bin:$HOME/.cargo/bin"

export NTFY_TOPIC=ping
export NTFY_TAGS="$HOSTNAME"

export NVIM_LSP_ENABLED=true
