#!/bin/bash
export $(envsubst < "$HOME/.config/environment.d/env.conf")

export PATH="$PATH:$XDG_DATA_HOME/nvim/mason/bin:$XDG_CONFIG_HOME/emacs/bin"

export NTFY_TOPIC=ping
export NTFY_TAGS="$HOSTNAME"

export NVIM_LSP_ENABLED=true
