#!/bin/bash

if command -v eza &>/dev/null; then
  alias ls='eza'
fi

if command -v pacman &>/dev/null; then
  alias p='pacman'
  alias pa='sudo pacman'

  alias reflectorupdate='sudo reflector -c CA,US --age 12 --fastest 20 --sort rate --protocol https --save /etc/pacman.d/mirrorlist'
  alias browse-pacman="pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'"
  alias browse-pacman-online="pacman -Slq | fzf --preview 'pacman -Si {}' --layout=reverse"
fi

alias la='ls -a'
alias n='nvim'
alias s='systemctl'
alias sy='sudo systemctl'
alias su='systemctl --user'
alias open='xdg-open'
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gl='git lg'
alias gd='git diff'
alias t='tmux'
alias ta='tmux attach-session'
alias tl='tmux list-sessions'
alias tn='tmux new-session'
alias tk='tmux kill-session'

# One-liner shortcuts
alias temp='cd $(mktemp -d)'
alias update-grub='sudo grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=GRUB'
alias webs='websocat --close-status-code 1000 -E'

# Tex package manager
alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode'

# cd shortcuts
alias update-cdd='fd -Ha -td -d1 -E "\.config" "^\." ~ > ~/.cddignore'
alias cdd='cd "$(fd -H -td --ignore-file ~/.cddignore . ~ | fzf --preview "exa -lF --no-permissions {}" --tiebreak=length,end,begin --preview-window=up,20%)"'
alias cdda='cd "$(fd -H -td . ~ /etc | fzf --preview "exa -lF --no-permissions {}" --tiebreak=length,end,begin --preview-window=up,20%)"'
alias cdf='cd "$(fd -H -tf --ignore-file ~/.cddignore . ~ | fzf --preview "bat --style=header-filename,header-filesize -r 40: --color=always {}" --tiebreak=length,end,begin --preview-window=up,20% | xargs dirname)"'
alias cdfa='cd "$(fd -H -tf . ~ /etc | fzf --preview "bat --style=header-filename,header-filesize -r 40: --color=always {}" --tiebreak=length,end,begin --preview-window=up,20% | xargs dirname)"'
alias cddh='cd "$(fd -H -td -E .git . | fzf --preview "exa -lF --no-permissions {}" --tiebreak=length,end,begin --preview-window=up,20%)"'
